---
- name: Deploy Container to Kubernetes
  hosts: kubernetes-master
  remote_user: devopsadmin
  become: true
  vars: 
    docker_registry: docker.io
    dockerhub_repo: dashshishir/devopsedu
    docker_image_tag: latest
  tasks:
    - name: create the deployment
      shell: |
        kubectl get nodes
