---
- name: Deploy Container to Kubernetes
  hosts: kubernetes
  remote_user: devopsadmin
  become: true
  vars: 
    docker_registry: docker.io
    dockerhub_repo: dashshishir/devopsedu
    docker_image_tag: latest
  tasks:
    - name: create the deployment
      shell: |
        pwd
        kubectl apply -f .\home\devopsadmin\workspace\cicd-train-schedule-app\ansible\deploy-playbook.yaml
    # - name: create the service
    #   shell: |
    #     kubectl apply -f .\kubernetes\service.yaml